### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by roeniss** [dart-lang/html#156]
I failed to parse html, but can't figure out why it happens because there are few log to check out.

```text
<div class="substance">
									<p><br></p><p align="center" style="margin: 1em 0px; text-align: center; line-height: 115%;"><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 14pt; mso-bidi-font-size: 11.0pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;"><font color="#000000">울산인재평생교육진흥원   <span lang="EN-US">2021 상</span>반기 장학생 선발 안내</font></span></b></p><p align="center" style="margin: 1em 0px; text-align: center; line-height: 115%;"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-bidi-font-size: 10.0pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;"><font color="#000000">&nbsp;</font></span></b></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">1. </span></b><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">장학금<span lang="EN-US">: </span>등록금 최대<span lang="EN-US"> 200</span>만원 또는 생활비<span lang="EN-US"> 70</span>만원 </span></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-bidi-font-size: 10.0pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">-   </span><b style="mso-bidi-font-weight: normal;"><u><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-bidi-font-size: 10.0pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">장학금  종류 및 지급액은 첨부의 선발 공고문 반드시 참조</span></u></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;"><font color="#000000">&nbsp;</font></span></b></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">2. </span></b><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">지원자격   </span></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">-&nbsp;울산시 소재 고등학교 졸업자로&nbsp;</span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast;">공고일  현재 본인 또는 보호자 주민등록상 울산 거주</span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">- </span></b><b><u><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">장학금별 지원자격은 첨부의 선발 공고문 반드시 참조</span></u></b><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;"> </span></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;"><font color="#000000">&nbsp;</font></span></b></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">3. </span></b><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">지원기간<span lang="EN-US">: 2021</span>년 3월 22일<span lang="EN-US">(</span>월<span lang="EN-US">)~4</span>월 9일<span lang="EN-US">(금</span><span lang="EN-US">)</span></span></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;"><span style="mso-spacerun: yes;"><font color="#000000">&nbsp;</font></span></span></b></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">4. </span></b><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">제출서류</span></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">장학생 지원 신청서 및 신청인 서약서</span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">개인정보 수집<span lang="EN-US">.</span>이용<span lang="EN-US">.</span>제공 및 조회 동의서</span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">주민등록등본 및 가족관계증명서</span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">등록금 납입 영수증 </span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">재학증명서 및 성적증명서 </span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">본인명의 통장 사본 </span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><b><u><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">장학금별 구비서류는 선발 공고문 반드시 참조</span></u></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><b><u><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;"><span style="text-decoration: none;"><font color="#000000"><br></font></span></span></u></b></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><b><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">5. </span></b><b><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;">접수방법<span lang="EN-US">: 전자신청 후 구비서류와 함께 </span>우편 제출</span></b></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕;"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- 전자신청: 울산인재평생교육진흥원 홈페이지(<a href="https://www.ulsaninjae.or.kr">https://www.ulsaninjae.or.kr</a>)</span></span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- 제출</span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">처<span lang="EN-US">: </span>울산광역시  남구 번영로<span lang="EN-US"> 224 4</span>층 울산인재평생교육진흥원<span lang="EN-US">(</span>우<span lang="EN-US">: 44702)</span></span></font></p><p style="margin: 1em 0px; line-height: 115%;"><font color="#000000"><span lang="EN-US" style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">- </span><span style="line-height: 115%; font-family: &quot;맑은 고딕&quot;; font-size: 11pt; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 함초롬바탕; mso-bidi-font-weight: bold;">문의전화<span lang="EN-US">:   052-288-7401</span></span></font><br></p>
								</div>
```

When I tried to `Html(data: thatHtml)`, my console: 

```bash
======== Exception caught by widgets library =======================================================
The following StateError was thrown building HtmlParser(dirty):
Bad state: No element

The relevant error-causing widget was: 
  Html file:///Users/kakao/workspace/sogangtips/lib/views/notice_view.dart:182:29
When the exception was thrown, this was the stack: 
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      declarationsToStyle.<anonymous closure> (package:flutter_html/src/css_parser.dart:49:52)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#3      declarationsToStyle (package:flutter_html/src/css_parser.dart:10:16)
#4      inlineCSSToStyle (package:flutter_html/src/css_parser.dart:78:10)
...
====================================================================================================
```

It would be great if there are more detailed error log. Or am I missing something?

**Comment by roeniss** [comment]
Actually this is pretty serious because I can't catch it before rendering: 

Widget build(BuildContext context){
  // ... 	  
  Widget content;
	  ```dart
	  try {
	    content = Html(data: webContent);
	  } catch (e) {
	    content = Text('Can't show detail');
	  }
  // ... 

  return content;
}
```

Above trycatch doesn't catch the exception.

**Comment by roeniss** [comment]
I think I'd better go to `flutter_html`. sorry to bother you guys.
